export const countrys = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antigua and Barbuda",
  "Argentina",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Bermuda",
  "Bolivia",
  "Brazil",
  "Bulgaria",
  "Cambodia",
  "Canada",
  "Cayman Islands",
  "Chile",
  "China",
  "Colombia",
  "Costa Rica",
  "Cote d'Ivoire",
  "Croatia",
  "Cyprus",
  "Czechia",
  "Denmark",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "England",
  "Equatorial Guinea",
  "Estonia",
  "Faeroe Islands",
  "Falkland Islands",
  "Finland",
  "France",
  "Germany",
  "Ghana",
  "Gibraltar",
  "Greece",
  "Greenland",
  "Grenada",
  "Guatemala",
  "Guernsey",
  "Guinea",
  "Guyana",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Ireland",
  "Isle of Man",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jersey",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kuwait",
  "Laos",
  "Latvia",
  "Lebanon",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macao",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Malta",
  "Mauritius",
  "Mexico",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Montserrat",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nigeria",
  "North Macedonia",
  "Northern Cyprus",
  "Northern Ireland",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Panama",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Helena",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "San Marino",
  "Saudi Arabia",
  "Scotland",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "South Africa",
  "South Korea",
  "Spain",
  "Sri Lanka",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Taiwan",
  "Thailand",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turks and Caicos",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Venezuela",
  "Vietnam",
  "Wales",
  "Zimbabwe",
];
export const codesCont = [
  'af', 'al', 'dz',     'ad', 'ao', 'ai',     'ag',     'ar',
  'au', 'at', 'az',     'bs', 'bh', 'bd',     'bb',     'by',
  'be', 'bz', 'bm',     'bo', 'br', 'bg',     'kh',     'ca',
  'ky', 'cl', 'cn',     'co', 'cr', 'ci',     'hr',     'cy',
  'cz', 'dk', 'dm',     'do', 'ec', 'eg',     'sv',     'gb-eng',
  'gq', 'ee', 'fo',     'fk', 'fi', 'fr',     'de',     'gh',
  'gi', 'gr', 'gl',     'gd', 'gt', 'gg',     'gn',     'gy',
  'hn', 'hk', 'hu',     'is', 'in', 'id',     'ir',     'ie',
  'im', 'il', 'it',     'jm', 'jp', 'je',     'jo',     'kz',
  'ke', 'kw', 'la',     'lv', 'lb', 'li',     'lt',     'lu',
  'mo', 'mw', 'my',     'mv', 'mt', 'mu',     'mx',     'md',
  'mc', 'mn', 'me',     'ms', 'ma', 'mz',     'mm',     'np',
  'nl', 'nz', 'ng',     'mk', 'mp', 'gb-nir', 'no',     'om',
  'pk', 'pw', 'pa',     'py', 'pe', 'ph',     'pl',     'pt',
  'qa', 'ro', 'ru',     'rw', 'sh', 'kn',     'lc',     'vc',
  'sm', 'sa', 'gb-sct', 'sn', 'rs', 'sc',     'sg',     'sk',
  'si', 'za', 'kr',     'es', 'lk', 'sr',     'se',     'ch',
  'tw', 'th', 'tt',     'tn', 'tr', 'tc',     'ug',     'ua',
  'ae', 'gb', 'us',     'uy', 've', 'vn',     'gb-wls', 'zw'
]
